name: unigraph
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - pymupdf
      - chromadb
      - sentence-transformers
      - tqdm
      - langchain-text-splitters
      - pdfplumber
      - openai
      - google-generativeai
      - python-dotenv
      - streamlit
      - deep-translator
